# Generated by Django 4.0.6 on 2024-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_celeryworker"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="worker_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="worker name"
            ),
        ),
    ]
