# Generated by Django 4.0.6 on 2023-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='previous_data',
            field=models.TextField(blank=True, null=True, verbose_name='previous data'),
        ),
    ]
