# Generated by Django 4.0.6 on 2024-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_task_worker_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="platform_task_id",
            field=models.IntegerField(
                help_text="Platform Task ID in case if Platform initiated some pipeline",
                null=True,
            ),
        ),
    ]
