# Generated by Django 4.0.6 on 2023-01-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_task_previous_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_hook',
            field=models.BooleanField(default=False, verbose_name='is hook'),
        ),
    ]
