# Generated by Django 4.0.6 on 2024-08-05 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('workflow', '0004_workflow_platform_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('user_code', models.TextField(verbose_name='user_code')),
                ('payload_data', models.TextField(blank=True, null=True, verbose_name='payload data')),
                ('is_manager', models.BooleanField(default=False, verbose_name='is manager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workflow.space', verbose_name='space')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('django_celery_beat.periodictask', models.Model),
        ),
        migrations.DeleteModel(
            name='CeleryWorker',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('init', 'INIT'), ('progress', 'PROGRESS'), ('success', 'SUCCESS'), ('error', 'ERROR'), ('timeout', 'TIMEOUT'), ('canceled', 'CANCELED')], default='init', max_length=255, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('init', 'INIT'), ('progress', 'PROGRESS'), ('success', 'SUCCESS'), ('error', 'ERROR'), ('timeout', 'TIMEOUT'), ('canceled', 'CANCELED')], default='init', max_length=255, null=True, verbose_name='status'),
        ),
    ]
