# Generated by Django 4.0.6 on 2023-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_task_is_hook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('init', 'INIT'), ('pending', 'PENDING'), ('progress', 'PROGRESS'), ('success', 'SUCCESS'), ('error', 'ERROR'), ('timeout', 'TIMEOUT'), ('canceled', 'CANCELED')], default='init', max_length=255, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('init', 'INIT'), ('pending', 'PENDING'), ('progress', 'PROGRESS'), ('success', 'SUCCESS'), ('error', 'ERROR'), ('timeout', 'TIMEOUT'), ('canceled', 'CANCELED')], default='init', max_length=255, null=True, verbose_name='status'),
        ),
    ]
