# Generated by Django 4.0.6 on 2023-01-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_task_status_alter_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='is bot'),
        ),
    ]
