# Generated by Django 4.0.6 on 2024-08-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('workflow', '0005_schedule_delete_celeryworker_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='crontab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows',
                                    to='django_celery_beat.crontabschedule', verbose_name='crontab'),
        ),
    ]
