# Generated by Django 4.0.6 on 2023-01-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_user_is_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'get_latest_by': 'modified', 'ordering': ['-created', 'id']},
        ),
    ]
