# Generated by Django 4.0.6 on 2024-10-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_workflow_crontab'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('user_code', models.CharField(blank=True, max_length=1024, null=True, verbose_name='user_code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='workflow.space', verbose_name='space')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
