# Generated by Django 4.0.6 on 2023-02-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_alter_workflow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='user_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user_code'),
        ),
    ]
