# Generated by Django 4.0.6 on 2023-03-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_workflow_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='finished at'),
        ),
    ]
