# Generated by Django 4.0.6 on 2023-04-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_task_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='project',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='user_code',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='user_code'),
        ),
    ]
