# Generated by Django 4.0.6 on 2023-04-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_remove_workflow_project_alter_workflow_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='is manager'),
        ),
    ]
