# Generated by Django 4.0.6 on 2024-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_task_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source_code',
            field=models.TextField(blank=True, null=True, verbose_name='source code'),
        ),
    ]
