# Generated by Django 4.0.6 on 2023-08-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_workflow_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='log'),
        ),
    ]
