# Generated by Django 4.0.6 on 2024-10-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_alter_task_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='current_node_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='last_task_output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('progress', 'progress'), ('wait', 'wait'), ('success', 'success'), ('error', 'error'), ('timeout', 'timeout'), ('canceled', 'canceled')], default='init', max_length=255, null=True, verbose_name='status'),
        ),
    ]
