# Generated by Django 4.0.6 on 2024-10-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_workflow_current_node_id_workflow_last_task_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='workflow_user_code',
            field=models.TextField(default='-', verbose_name='workflow_user_code'),
            preserve_default=False,
        ),
    ]
