# Generated by Django 4.0.6 on 2024-10-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_schedule_notes_schedule_workflow_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='execution_status',
            field=models.JSONField(blank=True, default=dict, help_text='Store all graph of nodes and status of its execution'),
        ),
    ]
