# Generated by Django 4.0.6 on 2024-10-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_workflow_execution_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='execution_status',
        ),
    ]
