# Generated by Django 4.0.6 on 2024-10-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_remove_workflow_execution_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'get_latest_by': 'modified', 'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'get_latest_by': 'modified_at', 'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='workflowtemplate',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workflowtemplate',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
