# Generated by Django 4.0.6 on 2024-10-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_alter_schedule_options_alter_space_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='finished_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='finished at'),
        ),
    ]
