# Generated by Django 4.0.6 on 2024-10-15 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_workflow_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='workflow.workflow', verbose_name='parent'),
        ),
    ]
