# Generated by Django 4.0.6 on 2024-10-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_workflow_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('init', 'INIT'), ('progress', 'PROGRESS'), ('nested-progress', 'nested-progress'), ('success', 'SUCCESS'), ('error', 'ERROR'), ('timeout', 'TIMEOUT'), ('canceled', 'CANCELED')], default='init', max_length=255, null=True, verbose_name='status'),
        ),
    ]
