# Generated by Django 4.0.6 on 2025-01-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_delete_repeated_workflow_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplate',
            unique_together={('user_code', 'space')},
        ),
    ]
