name: Tests workflow

on:
  workflow_call:

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    env:
      DB_NAME: test_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBITMQ_USER: test_finmars_user
      RABBITMQ_PASSWORD: test_finmars_password

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq:3.13-management-alpine
        env:
          RABBITMQ_DEFAULT_USER: test_finmars_user
          RABBITMQ_DEFAULT_PASS: test_finmars_password
        ports: 
          - 5672:5672
      redis:
        image: redis:7-alpine
        ports: 
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run tests
        run: |
          echo "Run some tests"
